language: c
script: make && make travis && ./src/sslproxy -V
matrix:
  include:
    - os: linux
      compiler: gcc
      env: SSL=ubuntu EVENT=ubuntu
      cache:
        directories:
          - $HOME/.cargo
      before_install:
        - sudo apt-get install -qq libssl-dev libevent-dev libnet1-dev libpcap-dev check
        # Do use the following line: curl https://sh.rustup.rs -sSf | sh
        # Download rustup.sh and run with -y, otherwise it stops and prompts for an answer
        - curl -f -L https://static.rust-lang.org/rustup.sh -O
        # Don't forget to add .cargo/bin to $PATH
        - sh rustup.sh -y && source $HOME/.cargo/env && cargo install testproxy
#    - os: linux
#      compiler: clang
#      env: SSL=openssl-1.1.1c EVENT=libevent-2.1.11
#      cache:
#        directories:
#          - $HOME/opt
#      before_install:
#        - sudo apt-get install -qq libnet1-dev libpcap-dev check
#        # Do use the following line: curl https://sh.rustup.rs -sSf | sh
#        # Download rustup.sh and run with -y, otherwise it stops and prompts for an answer
#        - curl -f -L https://static.rust-lang.org/rustup.sh -O
#        # Don't forget to add .cargo/bin to $PATH
#        - sh rustup.sh -y && source $HOME/.cargo/env && cargo install testproxy
#      install:
#        - ./Mk/bin/install-opt.sh
#      before_script:
#        - export OPENSSL_BASE="$HOME/opt/$SSL"
#        - export LIBEVENT_BASE="$HOME/opt/$EVENT"
#        - export LD_LIBRARY_PATH="$HOME/opt/$SSL/lib":"$HOME/opt/$EVENT/lib"
