language: c
script: make && make travis && ./src/sslproxy -V
matrix:
  include:
    - os: linux
      compiler: gcc
      env: SSL=ubuntu EVENT=ubuntu
      before_install:
        - sudo apt-get install -qq libssl-dev libevent-dev libnet1-dev libpcap-dev check
#        - curl https://sh.rustup.rs -sSf | sh
        - curl -f -L https://static.rust-lang.org/rustup.sh -O
        - sh rustup.sh -y
        - source $HOME/.cargo/env
        - cargo install testproxy
